# This is a basic workflow to help you get started with Actions

name: workflow inuts 테스트

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_env:
        description: '배포 위치'
        required: true
        default: 'dev'
        type: choice
        options:
          - prod
          - staging
          - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          branch_name=${GITHUB_REF##*/}
          echo "branch: $branch_name"
          echo "deploy_env: ${{ inputs.deploy_env }}"

          deploy_env=${{ inputs.deploy_env }}
          event_name=${{ github.event_name }}
          if [[ ${{ github.event_name }} == "push" && $branch_name == "develop" ]]
          then
            deploy_env=dev
          fi

          if [[ $deploy_env == "prod" && $branch_name != "main" ]]
          then
            echo "main 브랜치만 prod 환경에 배포할 수 있습니다. 현재 브랜치: $branch_name"
            deploy_env=undefined
          fi
          echo "deploy_env: $deploy_env"
